### ISSUE TITLE
react-native-google-code-scanner-android

### ISSUE THREAD

**Issue by arunjj** [anirudhabhurke/react-native-google-code-scanner-android#1]
android version 13 not working. showing error failed to scan code

**Comment by anirudhabhurke** [comment]
Hi, this is an intermittent [issue](https://issuetracker.google.com/issues/261579118) in some devices where the QR module is not loaded by Google Play Services.

I have released a new version (v1.1.1) where I added 2 functions `checkModuleAvailability` and `installModule` for you to check if the QR scanner module is installed or not. Visit the updated [docs](https://github.com/anirudhabhurke/react-native-google-code-scanner-android/tree/main?tab=readme-ov-file#usage) for details.

**Comment by arunjj** [comment]
thnx

**Comment by anirudhabhurke** [comment]
> thnx

Welcome. Hope you find the library helpful
